init_config:
instances:
  - collect_events: true
    collect_container_size: true
    collect_container_size_frequency: 60
    collect_images_stats: true
    collect_image_size: true
    collect_disk_stats: true
    collect_exit_codes: true